# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish Jar

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: 'string'
        default: '1.21.1-neoforge'
      mc_version:
        description: 'Minecraft Version'
        required: true
        type: 'string'
        default: '1.21.1'
      version:
        description: 'Version'
        required: true
        type: 'string'
        default: '2.3.0'
      version_type:
        description: 'Version Type'
        required: true
        type: 'choice'
        options:
          - 'alpha'
          - 'beta'
          - 'release'
        default: 'beta'
      publish_to_curseforge:
        description: 'Publish to CurseForge'
        required: true
        type: 'boolean'
        default: false
      publish_to_modrinth:
        description: 'Publish to Modrinth'
        required: true
        type: 'boolean'
        default: false
      publish_github_release:
        description: 'Publish GitHub Release'
        required: true
        type: 'boolean'
        default: true

env:
  JAVA_VERSION: 21

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build NeoForge Jar
        run: ./gradlew clean build -Pmod_version=${{ inputs.version }}

      - name: Publish NeoForge GitHub Release
        if: ${{ inputs.publish_github_release == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{ secrets.PUBLISH_TOKEN }}"

          name: "NeoForge ${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          version: "${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          github-tag: "${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          github-commitish: ${{ inputs.branch }}
          changelog-file: CHANGELOG.md
          files: build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{ inputs.version_type }}

          fail-mode: warn

      - name: Publish NeoForge CurseForge
        if: ${{ inputs.publish_to_curseforge == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 659897
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          name: "NeoForge ${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          version: "${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          changelog-file: CHANGELOG.md
          files: build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{ inputs.version_type }}
          java: |
            Java 21
          loaders: |
            neoforge
          game-versions: |
            ${{ inputs.mc_version }}

          dependencies: |
            IrisShader(required){modrinth:iris}{curseforge:455508}
            Sodium(required){modrinth:sodium}{curseforge:394468}
            Create(optional){modrinth:create}{curseforge:328085}

          fail-mode: warn


      - name: Publish NeoForge Modrinth
        if: ${{ inputs.publish_to_modrinth == true }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: iris-flw-compat
          modrinth-token: "${{ secrets.MODRINTH_TOKEN }}"

          name: "NeoForge ${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          version: "${{ inputs.mc_version }}+${{ inputs.version }}-${{ inputs.version_type }}"
          changelog-file: CHANGELOG.md
          files: build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar
          version-type: ${{ inputs.version_type }}
          java: |
            Java 21
          loaders: |
            neoforge
          game-versions: |
            ${{ inputs.mc_version }}

          dependencies: |
            IrisShader(required){modrinth:iris}{curseforge:455508}
            Sodium(required){modrinth:sodium}{curseforge:394468}
            Create(optional){modrinth:create}{curseforge:328085}

          fail-mode: warn
